    </footer>
        <div class="footer">
            <small>2021 © Copyright GRUPO 9 SI technologies.</small>
        </div>
    <footer>

    <!-- JQUERY -->
    <script src="<?php echo URL_ASSETS?>js/libs/jquery-3.6.1.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- JS PARA MÁSCARA DE INPUTS -->
    <script src="<?php echo URL_ASSETS?>js/libs/jquery.mask.min.js"></script>
    <script src="<?php echo URL_ASSETS?>js/mask.js"></script>

    <!-- SCRIPTS PERSONALIZADOS -->
    <script src="<?php echo URL_ASSETS?>js/val-login.js"></script>
    <script src="<?php echo URL_ASSETS?>js/val-cad-user.js"></script>
    <script src="<?php echo URL_ASSETS?>js/val-alter-password.js"></script>
    <script src="<?php echo URL_ASSETS?>js/val-cad-borracharia.js"></script>
    <script src="<?php echo URL_ASSETS?>js/utils.js"></script>
</body>
</html>