
    </footer>
        <div class="footer">
            <p>2021 © Copyright GRUPO 9 SI technologies.</p>
        </div>
    <footer>


    <!-- JQUERY -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>

    <!-- POPPER.JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <!-- BOOTSTRAP JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- LIBS DE MÁSCARA PARA INPUTS -->
    <script src="<?php echo URLASSETS?>js/jquery.mask.js"></script>
    <script src="<?php echo URLASSETS?>js/mask.js"></script>

    <!-- SCRIPTS PERSONALIZADOS -->
    <script src="<?php echo URLASSETS?>js/login.js"></script>
    <script src="<?php echo URLASSETS?>js/profile.js"></script>
</body>

</html>