<?php

if (!defined('URL')) {
    header("Location: /");
    exit();
}

?>
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- META TAGS -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/df04815b4a.js" crossorigin="anonymous"></script>

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo URL_ASSETS ?>css/style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo URL_ASSETS ?>css/modal.css">

    <!-- TÍTULO DO SITE -->
    <title>PNEWS</title>

    <!-- ICONE DO SITE -->
    <link rel="icon" href="<?php echo URL_ASSETS ?>img/logo/logo-titulo.png">

    <!-- DEFINE AS URL PADRÃO PARA O JS -->
    <script type="text/javascript">
        var URL = "<?php echo URL ?>";
        var URL_ASSETS = "<?php echo URL_ASSETS ?>";
    </script>
</head>

<body>
<div class="retorno-msg"></div>