<?php
if (session_status() == PHP_SESSION_ACTIVE) {
    session_destroy();
}
?>
<main>
    <div class="container">
        <div class="row vh-100">

            <!-- LOGO -->
            <div class="col-5 d-none d-lg-block align-self-center">
                <div class="row justify-content-center">
                    <img class="size-img" src="<?php echo URL_ASSETS ?>img/logo/logo-pnews.svg" alt="Logo Pnews">
                </div>

                <div class="row justify-content-center">
                    <img class="size-img" src="<?php echo URL_ASSETS ?>img/logo/mascote.svg" alt="Mascote Pnews">
                </div>

                <p class="mb-5 text-center error-status"><strong>ERRO!</strong></p>
            </div>


            <!-- MENSAGEM -->
            <div class="col col-lg-7">
                <div class="container cor-fundo">
                    <div class="w-100 row justify-content-center vh-100">
                        <div class="col-10 col-sm-8 text-center align-self-center">
                            <p class="error-404-text mb-0"><strong>ERRO</strong></p>
                            <p class="mb-5 error-404-text"><strong>404</strong></p>

                            <p class="mb-5 error-msg">Página não encontrada!</p>

                            <a href="<?php echo URL ?>login-controller/index" class="mt-0 btn btn-outline-danger btn-lg borda"> Voltar</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>