<?php
if (isset($_SESSION['error'])) {
    extract($_SESSION['error'])
?>
    <main>
        <div class="container">
            <div class="row vh-100">

                <!-- LOGO -->
                <div class="col-5 d-none d-lg-block align-self-center">
                    <div class="row justify-content-center">
                        <img class="size-img" src="<?php echo URL_ASSETS ?>img/logo/logo-pnews.svg" alt="Logo Pnews">
                    </div>

                    <div class="row justify-content-center">
                        <img class="size-img" src="<?php echo URL_ASSETS ?>img/logo/mascote.svg" alt="Mascote Pnews">
                    </div>

                    <p class="mb-5 text-center error-status"><strong><?php echo $status ?>!</strong></p>
                </div>


                <!-- MENSAGEM -->
                <div class="col col-lg-7">
                    <div class="container cor-fundo">
                        <div class="row justify-content-center vh-100">
                            <div class="w-100 col-10 col-sm-8 text-center align-self-center">
                                <p class="error-default-text mb-0"><strong>Atenção!</strong></p>

                                <p class="mb-5 error-msg"> <?php echo $msgError ?></p>

                                <a href="<?php echo URL . $redirect ?>" class="mt-0 btn btn-outline-danger btn-lg borda"><?php echo $nameButton ?></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </main>
<?php
    if (strtolower($sessionDestroy) == 's') {
        if (session_status() == PHP_SESSION_ACTIVE) {
            session_destroy();
        }
    }

    unset($_SESSION['error']);
} else {
    header("location: " . URL . "error-controller/error/404");
}
?>