<main>
    <div class="container">
        <div class="row vh-100">

            <!-- LOGO -->
            <div class="col-5 d-none d-lg-block align-self-center">
                <div class="row justify-content-center">
                    <img src="<?php echo URLASSETS ?>img/logo/logo-pnews-login.svg" alt="Logo Pnews">
                </div>

                <div class="row justify-content-center">
                    <img src="<?php echo URLASSETS ?>img/logo/mascote.svg" width="509" height="475" alt="Mascote Pnews">
                </div>
            </div>

            <!-- LOGIN -->
            <div class="col col-lg-7">
                <div class="container cor-fundo">
                    <div class="row justify-content-center vh-100">
                        <div class="col-10 col-sm-8 text-center align-self-center">
                            <h2 class="mb-5"><strong>Login</strong></h2>

                            <form id="form-send-login" class="mb-5">
                                <input class="form-control borda" id="email" type="text" name="email" placeholder="E-mail">
                                <br>
                                <input class="form-control borda" id="senha" type="password" name="senha" placeholder="Senha">

                                <br>
                                <a href="#" class="link-secondary"><u>Esqueceu a senha?</u></a>
                                <br>

                                <!-- Futuramente implementar login com APIS 
                                <div class="m-5">
                                    <a href="#" class="btn">
                                        <i class="fab fa-facebook-square fa-3x"></i>
                                    </a>
                                    
                                    <a href="#" class="btn">
                                        <i class="fab fa-google-plus-square fa-3x"></i>
                                    </a>
                                </div>
                                -->

                                <button id="btn-send-login" class="btn btn-outline-danger btn-lg borda mt-4" type="submit">Continuar</button>
                            </form>

                            <a href="<?php echo URL ?>cad-user-controller/index" class="link-secondary h5"> Cadastre-se grátis</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>

<script>
    // FUNCTION PARA ENVIAR O FORMULÁRIO
    document.getElementById('btn-send-login').onclick = function(e) {
        e.preventDefault();
        sendLogin();
    };

    async function sendLogin() {
        const form = new FormData(document.getElementById('form-send-login'));
    
        const response = await fetch('<?php echo URL ?>login-controller/validate-login', {
            method: 'POST',
            Headers: {
                'Content-type': 'application/json: charset-utf-8',
            },
            body: form
        });

        json = await response.json();

        if (json.cod === 0) {
            window.location.assign(URL + "home-Controller/index");

        } else {
            const retornoMsg = document.querySelector('.retornoMsg');
            retornoMsg.classList.add('retornoError');
            retornoMsg.style.display = "block";
            retornoMsg.innerHTML = json.msg;

            setTimeout(function() {
                retornoMsg.style.display = "none";
                retornoMsg.classList.remove('retornoError');
            }, 3000);
        }
    }
</script>