<main>
    <div class="container h-100">
        <div class="row justify-content-center h-100">
            <div class="col col-lg-9 col-xl-7 align-self-center">
                <div class="botao" style>
                    <a href="<?php echo URL ?>maps-controller/index">
                        <img src="<?php echo URL_ASSETS ?>img/site/botao-procure-borracharias.svg" class="img-fluid" alt="Procurar Borracharias">
                    </a>
                </div>
            </div>
        </div>
    </div>
</main>