<main class="main-custom">
    <div class="container h-100 pt-md-3 pb-5">
        <div class="row justify-content-center h-100">
            <div class="col">

                <!-- DIV QUE É EXIBIDO O MAPA -->
                <div id="map"></div>

            </div>
        </div>
    </div>
</main>

<div class="d-none">
    <button type="hidden" class="btn btn-primary" name="showModal" id="showModal" data-toggle="modal" data-target="#modalIncludeMaps">
        modal
    </button>
</div>

<!-- MODAL -->
<div class="modal fade t-modal" id="modalIncludeMaps" tabindex="-1" role="dialog" aria-labelledby="modalAlterarSenha" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            <div class="modal-header text-center">
                <h5 class="modal-title">Cadastro de Oficina</h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div class="container-fluid">

                    <div class="row justify-content-and">
                        <div class="col-12 text-center align-self-center">

                            <form id="form-cad-oficina" style="margin: 10px 20px 10px 20px;">
                                <input type="hidden" name="type" id="type" value="2">

                                <input class="form-control mt-2 borda" type="text" name="nome" id="nome" placeholder="Nome da oficina">

                                <input class="form-control mt-2 borda phone" type="text" name="telefone" id="telefone" placeholder="Telefone oficina">

                                <input class="form-control mt-2 borda" type="text" name="email" id="email" placeholder="E-mail oficina">

                                <input type="text" name="coords" id="coords" hidden>
                            </form>

                        </div>
                    </div>

                    <div class="row">
                        <div class="col text-center borda-form p-0">
                            <button id="btn-cad-oficina" class="btn btn-secondary btn-block rounded-0 m-0 btn-custom"> Enviar</button>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
<!-- FIM MODAL -->

<script>
    window.onload = () => {
        getOficinas();
    }

    // FUNCTION PARA PEGAR OFICINAS CADASTRADAS
    async function getOficinas() {
        const response = await fetch(URL + 'maps-oficina-controller/get-oficinas', {
            method: 'POST',
            Headers: {
                'Content-type': 'application/json: charset-utf-8',
            }
        });

        json = await response.json();

        if (json.cod === 0) {

            oficina = json.res;
            initMap(oficina);

        } else {
            const retornoMsg = document.querySelector('.retorno-msg');
            retornoMsg.classList.add('retorno-error');
            retornoMsg.style.display = "block";
            retornoMsg.innerHTML = json.msg;

            setTimeout(function() {
                retornoMsg.style.display = "none";
            }, 5000);

            initMap();
        }
    }

    // FUNCTION PARA ENVIAR O FORMULÁRIO 
    document.querySelector('#btn-cad-oficina').onclick = function(e) {
        document.querySelector('#btn-cad-oficina').disabled = true;
        e.preventDefault();

        validate = validateCadEstablishment();

        if(validate){
            cadOficina();
        } else {
            document.querySelector('#btn-cad-oficina').disabled = false;
        }
    };

    async function cadOficina() {
        const form = new FormData(document.querySelector('#form-cad-oficina'));

        const response = await fetch(URL + 'maps-oficina-controller/cad-oficina', {
            method: 'POST',
            Headers: {
                'Content-type': 'application/json: charset-utf-8',
            },
            body: form
        });

        json = await response.json();

        if (json.cod === 0) {
            const retornoMsg = document.querySelector('.retorno-msg');
            retornoMsg.classList.add('retorno-success');
            retornoMsg.style.display = "block";
            retornoMsg.innerHTML = json.msg;

            setTimeout(function() {
                retornoMsg.style.display = "none";
                retornoMsg.classList.remove('retorno-success');
                document.querySelector('#btn-cad-oficina').disabled = false;
            }, 10000);

        } else {
            const retornoMsg = document.querySelector('.retorno-msg');
            retornoMsg.classList.add('retorno-error');
            retornoMsg.style.display = "block";
            retornoMsg.innerHTML = json.msg;

            setTimeout(function() {
                retornoMsg.style.display = "none";
                retornoMsg.classList.remove('retorno-error');
                document.querySelector('#btn-cad-oficina').disabled = false;
            }, 10000);
        }
    }

    // LOCALIZAÇÃO PADRÃO SE CASO O USUÁRIO NÃO PERMITIR USAR SUAS COORDENADAS
    var lat = -23.551260514373695;
    var lng = -46.63441780394384;

    function initMap() {

        // DEFINE CUSTOMIZAÇÕES INICIAIS E INSTÃNCIA O MAPA
        const map = new google.maps.Map(document.querySelector("#map"), {
            zoom: 13,
            center: {
                lat: lat,
                lng: lng
            },
            styles: [{
                "featureType": "poi",
                "stylers": [{
                    "visibility": "off"
                }]
            }]
        });

        // MARCADOR DA LOCALIZÃO ATUAL DO USUÁRIO
        const marker = new google.maps.Marker({
            position: {
                lat: lat,
                lng: lng
            },
            map: map,
        });

        // PEGA AS COORDENADAS DO USUÁRIO
        navigator.geolocation.watchPosition(success, error);

        // EXIBE OS ERROS CASO A API NÃO CONSEGUIR PEGAR AS COORDENADAS DO USUÁRIO
        function error(error) {
            switch (error.code) {
                case error.PERMISSION_DENIED:
                    showMsg("Erro C300: Você rejeitou a permissão de localização.")
                    break;

                case error.POSITION_UNAVAILABLE:
                    showMsg("Erro C310: Sua localização está indisponível. Se o erro persistir entre em contato com nosso atendimento")
                    break;

                case error.TIMEOUT:
                    showMsg("Erro C320: O tempo da requisição da sua localização expirou.")
                    break;

                case error.UNKNOWN_ERROR:
                    showMsg("Erro C330: Sua localização está indisponível. Se o erro persistir entre em contato com nosso atendimento")
                    break;
            }

            function showMsg(msgError){
                const retornoMsg = document.querySelector('.retorno-msg');
                retornoMsg.classList.add('retorno-error');
                retornoMsg.style.display = "block";
                retornoMsg.innerHTML = msgError;

                setTimeout(function() {
                    retornoMsg.style.display = "none";
                    retornoMsg.classList.remove('retorno-error');
                    document.querySelector('#btn-cad-oficina').disabled = false;
                }, 5000);
            }
        }

        // SETA AS COORDENADAS DO USUÁRIO
        function success(position) {
            marker.setPosition({
                lat: position.coords.latitude,
                lng: position.coords.longitude
            });

            map.setCenter({
                lat: position.coords.latitude,
                lng: position.coords.longitude
            });
        }

        // CRIA MARCADORES ALEATÓRIOS DE FORMA DINÂMICA (REMOVER ESSE LOOP PHP E FAZER EM JS)
        oficina.map((oficina) => {
            var markers = [{
                coords: {
                    lat: parseFloat(oficina.coords_lat),
                    lng: parseFloat(oficina.coords_lng)
                },
                content: `<div dir="ltr" jstcache="0">` +
                    `<div jstcache="34" class="poi-info-window gm-style">` +

                    `<div jstcache="2">` +
                    `<div jstcache="3" class="title full-width" jsan="7.title,7.full-width">${oficina.nome}</div>` +

                    `<div class="address">` +
                    `<div jstcache="4" jsinstance="0" class="address-line full-width" jsan="7.address-line,7.full-width"> R: ${oficina.rua} , ${oficina.numero} - ${oficina.complemento} ${oficina.bairro} </div>` +
                    `<div jstcache="4" jsinstance="1" class="address-line full-width" jsan="7.address-line,7.full-width"> ${oficina.cidade}  - ${oficina.estado} </div>` +
                    `<div jstcache="4" jsinstance="2" class="address-line full-width" jsan="7.address-line,7.full-width"> ${oficina.nome} </div>` +
                    `</div>` +
                    `</div>` +

                    `<div jstcache="5" style="display:none"></div>` +

                    `<div>` +
                    `<a jstcache="6" href="tel:+55 ${oficina.telefone}" tabindex="0"><span>Ligar para: +55 ${oficina.telefone} </span></a>` +
                    `</div>` +

                    `</div>` +
                    `</div>`
            }];


            addMarker(markers[0]);
        });

        // CRIA OS MARCADORES NO MAPA
        function addMarker(data) {
            var markerBd = new google.maps.Marker({
                position: data.coords,
                map: map,
                icon: URL_ASSETS + 'img/maps/icon_maps.png'
            })

            if (data.content) {
                var infoWindow = new google.maps.InfoWindow({
                    content: data.content
                });

                markerBd.addListener('click', function() {
                    infoWindow.open(map, markerBd);
                });
            }
        }

        // ABRE MODAL PARA ADICIONAR NOVA OFICINA
        google.maps.event.addListener(map, 'click', function(event) {
            const inputCoords = document.querySelector("#coords");
            inputCoords.value = event.latLng;
            document.querySelector("#showModal").click();
        });
    }
</script>

<script async src="https://maps.googleapis.com/maps/api/js?key=<?php echo KEY_MAPS ?>"></script>